#!/bin/bash
IFS='
'
FILES=*.mp4
for NAME in $FILES
do
  DIR=$(echo $NAME | cut -f 1 -d '.' | tr -cd [:alnum:])
  echo "creating directory $DIR"
  mkdir $DIR
  sleep 5
  echo "Processing $NAME..."
  ffmpeg -i $NAME ./$DIR/%4d.png
  ffmpeg -i $NAME -vn -acodec pcm_s16le -ar 44100 -ac 2 ./$DIR/audio-track.wav
done
